"""Deterministic constants for the motorcycle simulation.

Source of truth:
- Reference, Chapters 0, 1, and 2.
- User-approved execution overrides recorded in README.md.

No business rule is inferred outside those sources.
"""

from __future__ import annotations

from datetime import date
from typing import Dict, Final, Optional, Tuple


# Chapter 2.1 — temporal constants
PROJECT_START_DATE: Final[date] = date(2027, 1, 1)
INITIAL_FLEET_PURCHASE_DATE: Final[date] = date(2026, 12, 26)
INITIAL_FLEET_READY_DATE: Final[date] = date(2027, 1, 1)
INITIAL_FLEET_DELIVERY_DATE: Final[date] = date(2027, 1, 2)
BIKE_PREP_SCHEDULE_DAYS: Final[int] = 6
PRIMARY_CONTRACT_MONTHS: Final[int] = 24
SECONDARY_CONTRACT_DURATION: Final[Optional[int]] = None  # open-ended
EXPANSION_CUTOFF_DATE: Final[date] = date(2030, 12, 31)
FINAL_CLOSE_DATE: Final[Optional[date]] = None  # dynamic; no fixed date


# Chapter 2.2 — financial/opening constants
TOTAL_CAPITAL: Final[int] = 3_700_000
BIKE_BASE_PURCHASE_COST: Final[int] = 350_000
CUSTOMS_COST: Final[int] = 5_000
REGISTRATION_COST: Final[int] = 5_000
CUSTOMS_AND_REGISTRATION_COST: Final[int] = 10_000
BIKE_GROSS_ASSET_COST: Final[int] = 360_000
PREP_OIL_COST: Final[int] = 2_000
PREP_LUBE_COST: Final[int] = 2_000
PREP_OPERATING_EXPENSE_PER_BIKE: Final[int] = 4_000
BIKE_TOTAL_CASH_FLOW_COST: Final[int] = 364_000
EXPANSION_PURCHASE_CASH_THRESHOLD: Final[int] = 350_000
FULL_PREP_CASH_REQUIREMENT: Final[int] = 14_000
PRIMARY_DAILY_RENT: Final[int] = 1_500
SECONDARY_DAILY_RENT: Final[int] = 1_000
SETTLEMENT_DAILY_RENT: Final[int] = 1_500
FRIDAY_FEE: Final[int] = 1_000
OIL_SERVICE_COST: Final[int] = 2_000
DEPRECIATION_RATE_PER_DAY: Final[int] = 50
MAX_DEPRECIATION: Final[int] = 360_000
PARTNER1_FINAL_SHARE_PCT: Final[int] = 70
PARTNER2_FINAL_SHARE_PCT: Final[int] = 30
OPENING_CASH: Final[int] = 0
OPENING_MARKETING_EXPENSE: Final[int] = 60_000
OPENING_PREP_EXPENSE: Final[int] = 40_000
OPENING_RETAINED_LOSS: Final[int] = -100_000
OPENING_BIKE_ASSETS: Final[int] = 3_600_000
INITIAL_FLEET_SIZE: Final[int] = 10
OPENING_PARTNER1_REINVESTMENT_BALANCE: Final[int] = 0
OPENING_PARTNER2_REINVESTMENT_BALANCE: Final[int] = 0


# Chapter 2.3 — default/state thresholds
PRIMARY_DEFAULT_AMOUNT: Final[int] = 45_000
SECONDARY_DEFAULT_AMOUNT: Final[int] = 10_000
WAITING_PRIMARY_UPPER: Final[int] = 31_500
NOTICE_PRIMARY_UPPER: Final[int] = 42_000
GRACE_PRIMARY_UPPER: Final[int] = 45_000
SETTLEMENT_PERIOD_DAYS: Final[int] = 30


# Chapter 2.4 — guarantee claim waiting periods, calendar days
PRIMARY_EARLY_TERMINATION_WAIT_DAYS: Final[int] = 30
SECONDARY_EARLY_TERMINATION_WAIT_DAYS: Final[int] = 20
POST_MATURITY_SETTLEMENT_FAILURE_WAIT_DAYS: Final[int] = 60
ADMINISTRATIVE_CLOSURE_WAIT_DAYS: Final[int] = 0
FINAL_CLOSURE_WAIT_DAYS: Final[int] = 0

CLAIM_SOURCE_PRIMARY_EARLY_TERMINATION: Final[str] = "PRIMARY_EARLY_TERMINATION"
CLAIM_SOURCE_SECONDARY_EARLY_TERMINATION: Final[str] = "SECONDARY_EARLY_TERMINATION"
CLAIM_SOURCE_POST_MATURITY_SETTLEMENT_FAILURE: Final[str] = "POST_MATURITY_SETTLEMENT_FAILURE"
CLAIM_SOURCE_ADMINISTRATIVE_CLOSURE: Final[str] = "ADMINISTRATIVE_CLOSURE"
CLAIM_SOURCE_FINAL_CLOSURE: Final[str] = "FINAL_CLOSURE"

CLAIM_WAITING_PERIODS_DAYS: Final[Dict[str, int]] = {
    CLAIM_SOURCE_PRIMARY_EARLY_TERMINATION: PRIMARY_EARLY_TERMINATION_WAIT_DAYS,
    CLAIM_SOURCE_SECONDARY_EARLY_TERMINATION: SECONDARY_EARLY_TERMINATION_WAIT_DAYS,
    CLAIM_SOURCE_POST_MATURITY_SETTLEMENT_FAILURE: POST_MATURITY_SETTLEMENT_FAILURE_WAIT_DAYS,
    CLAIM_SOURCE_ADMINISTRATIVE_CLOSURE: ADMINISTRATIVE_CLOSURE_WAIT_DAYS,
    CLAIM_SOURCE_FINAL_CLOSURE: FINAL_CLOSURE_WAIT_DAYS,
}


# Chapter 2.5 — Monte Carlo/RNG constants
MASTER_SEED: Final[int] = 20270101
COLLECTION_PROBABILITIES: Final[Tuple[float, ...]] = (1.00, 0.85, 0.70, 0.50, 0.30)
GUARANTEE_RECOVERY_RATES: Final[Tuple[int, ...]] = (100, 70, 50, 30, 0)
MONTE_CARLO_SCENARIO_COUNT: Final[int] = 25

# The original reference's gate-(A) comparison rule.
ABSOLUTE_EPSILON: Final[int] = 1
REFERENCE_EPSILON: Final[float] = 1e-6
REFERENCE_STABILITY_RELATIVE_TOLERANCE: Final[float] = 0.01

# User-approved statistical execution rule.
C100_STATISTICAL_START_TRIALS: Final[int] = 1
NON_C100_STATISTICAL_START_TRIALS: Final[int] = 300
ITERATION_ESCALATION_STEP: Final[int] = 50
STATISTICAL_CHECK_START_N: Final[int] = 300
STATISTICAL_CHECK_STEP_N: Final[int] = 50
MINIMUM_STOP_N_FOR_NON_C100: Final[int] = 400
STABILITY_CONSECUTIVE_CHECKS_REQUIRED: Final[int] = 3
INITIAL_SMOKE_TRIALS_PER_SCENARIO: Final[int] = 1

# C100 has no CI gate at n=1.
C100_CI_GATE_ENABLED: Final[bool] = False
CI_ABSOLUTE_EPSILON: Final[int] = 1
CI_CONFIDENCE_LEVEL: Final[float] = 0.95
CI_RELATIVE_TOLERANCE: Final[float] = 0.01

# Stability indicators under the user-approved definition.
STABILITY_INDICATOR_FINAL_NET_EQUITY: Final[str] = "Final_Net_Equity"
STABILITY_INDICATOR_P1: Final[str] = "Partner1_Final_Entitlement"
STABILITY_INDICATOR_P2: Final[str] = "Partner2_Final_Entitlement"

# Reference gate-(A) indicator set.
REFERENCE_STABILITY_INDICATORS: Final[Tuple[str, ...]] = (
    "P10_Cumulative_Project_Profit",
    "P50_Cumulative_Project_Profit",
    "P90_Cumulative_Project_Profit",
    "P90_Final_Cash",
    "Probability_of_Accounting_Loss",
    "P90_Termination_Count",
    "P90_Held_Assets",
)

# Derived immutable scenario identifiers.
SCENARIO_IDS: Final[Tuple[str, ...]] = tuple(
    f"C{int(probability * 100):03d}_G{recovery_rate:03d}"
    for probability in COLLECTION_PROBABILITIES
    for recovery_rate in GUARANTEE_RECOVERY_RATES
)

STATISTICAL_START_TRIALS_BY_COLLECTION: Final[Dict[float, int]] = {
    1.00: C100_STATISTICAL_START_TRIALS,
    0.85: NON_C100_STATISTICAL_START_TRIALS,
    0.70: NON_C100_STATISTICAL_START_TRIALS,
    0.50: NON_C100_STATISTICAL_START_TRIALS,
    0.30: NON_C100_STATISTICAL_START_TRIALS,
}


# Deterministic integrity checks only; no simulation is run.
assert len(COLLECTION_PROBABILITIES) == 5
assert len(GUARANTEE_RECOVERY_RATES) == 5
assert len(SCENARIO_IDS) == MONTE_CARLO_SCENARIO_COUNT
assert PARTNER1_FINAL_SHARE_PCT + PARTNER2_FINAL_SHARE_PCT == 100
assert BIKE_GROSS_ASSET_COST == BIKE_BASE_PURCHASE_COST + CUSTOMS_AND_REGISTRATION_COST
assert PREP_OPERATING_EXPENSE_PER_BIKE == PREP_OIL_COST + PREP_LUBE_COST
assert BIKE_TOTAL_CASH_FLOW_COST == (
    BIKE_BASE_PURCHASE_COST
    + CUSTOMS_AND_REGISTRATION_COST
    + PREP_OPERATING_EXPENSE_PER_BIKE
)
assert FULL_PREP_CASH_REQUIREMENT == (
    PREP_OPERATING_EXPENSE_PER_BIKE + CUSTOMS_AND_REGISTRATION_COST
)
assert WAITING_PRIMARY_UPPER == 21 * PRIMARY_DAILY_RENT
assert NOTICE_PRIMARY_UPPER == 28 * PRIMARY_DAILY_RENT
assert GRACE_PRIMARY_UPPER == PRIMARY_DEFAULT_AMOUNT
assert SECONDARY_DEFAULT_AMOUNT == 10 * SECONDARY_DAILY_RENT
assert MAX_DEPRECIATION == BIKE_GROSS_ASSET_COST
assert OPENING_PREP_EXPENSE == INITIAL_FLEET_SIZE * PREP_OPERATING_EXPENSE_PER_BIKE
assert OPENING_RETAINED_LOSS == -(
    OPENING_MARKETING_EXPENSE + OPENING_PREP_EXPENSE
)
assert TOTAL_CAPITAL - OPENING_BIKE_ASSETS + OPENING_RETAINED_LOSS == OPENING_CASH
